name: 강병영
description: 카르페디엠
avatar: https://lh3.googleusercontent.com/-LITB2XPacmw/XKDlAAeQ-mI/AAAAAAAAAC4/0RaeagHdwjABcaTOCYgvh1N9XO2lSijwwCEwYBhgLKs0DAL1OcqwASHNlJBabvWRNzO9amoXI9XMoKOgoY8eph6PZ8UibTzv4-gIuLE0FD3yOMfaIaGoG2KnNNOvoNjjTtbrPW-Qjj63-ddkYvDGrXkZ1sXGpO9yO_0tc04Ql-y_wy6H2aoqv53pYhdJ_TO50iRGKtdLPnvl4x3lwnH-rIR7hixpDyYNDNgH4stYLfQ337WdMi2Gk2VCKIOHv_xsArEciGmqE96BkjCgPUwsAIuotfOuOx14M7RpCHXG5xpAZcj6A00t0wDWu9Bp_Sr1lWvvmimYrUAXDiC2nYBejOLTMrgnUZ97OQVnMic0Mvm-BewUtk7PsVyfbQCO-C-gFzPvKPbh_OZJ5m_bWwsAI-mM-LF8sgO55oHKNO4ADdzbxUzl2VidrJCJjEXpn9N6lwsf4L3tudDExPEmm0VsQCBsqr5yMFKodFz6TnE8wVThfi1E1T1mjQfpR4J6-HiAdCPSOFMgIGuxUfZWIwMVa25AcQdlz8bvdX3_2hbxF1MBk02jei5lmI03AbdXFOl-36SJhZyzRYixcmJqW0xtvCqUCd_vb1xG_mdtw4TDQM_axEVjWCKSsChakvbRKSJojA2oO3vOMEFNgnQH_FJoww8mD9gU/w139-h140-p/photoman.png

navigation:
  - name: Home
    url: /
  - name: TIL
    url: /til
  - name: Archive
    url: /archive
  - name: About
    url: /about
  # - name: Tags
  #   url: /tags
  - name: app-ads
    url: /app-ads.txt

paginate: 5

footer-links:
  behance:
  dribbble:
  email: bykang096@gmail.com
  facebook:
  flickr:
  github: byeongyeong
  googleplus:
  instagram:
  linkedin:
  pinterest:
  rss:
  stackoverflow:
  tumblr:
  twitter: 
  youtube:

footer-text: Theme by kiko-now

google_analytics: UA-166875445-1
url: https://rokang.github.io/
baseurl:
permalink: /:title/
paginate_path: /page:num/
version: v1.2.0

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existin g pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  #- jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

# SEO variable
title: 강병영의 블로그
author: 강병영
social:
  name: 강병영
  links: